/**
 * Hero “brand tile” grid — swap logo assets / hex when you have final brand kits.
 * `brandBg` fills the tile; `accent` + `secondary` are brand tones for tile treatments.
 */
export const SHOWCASE_GRID_COUNT = 6

export const SHOWCASE_PROJECTS = [
  {
    slug: 'golden-state-capital-investment',
    client: 'Golden State Capital Investment',
    label: 'Golden State Capital',
    title: 'Plataforma de inversiones en bienes raíces',
    liveUrl: 'https://example.com',
    imageSrc: '/goldenstate.png',
    brandBg: '#0d2642',
    accent: '#ac8b49',
    secondary: '#224066',
    monogram: 'GS',
  },
  {
    slug: 'coach-fernando-quintero',
    client: 'Coach Fernando Quintero',
    label: 'Coach Fernando Quintero',
    title: 'Página de presentación y plataforma personalizada',
    liveUrl: 'https://example.com',
    imageSrc: '/ferquintero.png',
    brandBg: '#0a0a0f',
    accent: '#3a18b1',
    secondary: '#F59E0B',
    monogram: 'FQ',
  },
  {
    slug: 'havoc-undr-heaven',
    client: 'Havoc Undr Heaven',
    label: 'Havoc Undr Heaven',
    title: 'Plataforma de contenido + newsletter',
    liveUrl: 'https://example.com',
    imageSrc: '/havoc.png',
    brandBg: '#0A0A0A',
    accent: '#FFFFFF',
    secondary: '#1A1A1A',
    monogram: 'HUH',
  },
  {
    slug: 'chipxy-jewelry',
    client: 'Chipxy Jewelry',
    label: 'Chipxy Jewelry',
    title: 'E-commerce para una marca de joyería',
    liveUrl: 'https://example.com',
    imageSrc: '/chipxy.png',
    brandBg: '#1E1E1E',
    accent: '#ECFFB0',
    secondary: '#FBFFFD',
    monogram: 'CJ',
  },
  {
    slug: 'stemcell-mx',
    client: 'Stemcell MX',
    label: 'Stemcell MX',
    title: 'Sitio web para clínica México–EE.UU.',
    liveUrl: 'https://example.com',
    imageSrc: '/stemcellmx.png',
    brandBg: '#002B2B',
    accent: '#45EDB9',
    secondary: '#CCEDEC',
    monogram: 'SC',
  },
  {
    slug: 'contact-cta',
    client: 'Contacto',
    title: 'Hablemos de tu proyecto',
    liveUrl: '/contact',
    imageSrc: '',
    brandBg: '#111113',
    accent: 'rgba(87, 191, 190, 0.55)',
    secondary: 'rgba(87, 191, 190, 0.24)',
    monogram: '→',
    cta: true,
  },
]
